### ISSUE TITLE
When is it available in App Store (homey) 

### ISSUE THREAD

**Issue by Sjalabert** [erwindon/com.dondorp.homey.byrondb#1]
Will buy you an beer ;)

**Comment by erwindon** [comment]
Sorry for the delay...
The app will be published in the store as soon as it works properly.
But I have a little trouble decoding the protocol...

**Comment by Sjalabert** [comment]
when do you expect to be available?

**Comment by Sjalabert** [comment]
hello :)

**Comment by erwindon** [comment]
I'm soooo busy with other stuff, good that you push me... 👍 
The pairing has never really worked anyway.
The remaining problem is that each button-press seems to send a different signal each time.
The good news is that it is alternating nicely between 2 values.
But further bad news is that when Homey sends out these signals, the bell does not ring (but that may not be everyone's priority)

e.g. a recording of 6 button presses:
buttonId: [1,0,1,0,0,1,1,0,1,0,1,1,1,0,0,1,0,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0]=2797152876
buttonId: [0,0,0,1,0,0,1,0,1,1,0,1,0,1,1,0,0,1,1,1,1,0,1,0,0,0,1,0,1,1,0,0]=316045868
buttonId: [1,0,1,0,0,1,1,0,1,0,1,1,1,0,0,1,0,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0]=2797152876
buttonId: [0,0,0,1,0,0,1,0,1,1,0,1,0,1,1,0,0,1,1,1,1,0,1,0,0,0,1,0,1,1,0,0]=316045868
buttonId: [1,0,1,0,0,1,1,0,1,0,1,1,1,0,0,1,0,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0]=2797152876
buttonId: [0,0,0,1,0,0,1,0,1,1,0,1,0,1,1,0,0,1,1,1,1,0,1,0,0,0,1,0,1,1,0,0]=316045868

I'll still try to get it working, but it may not actually happen, sorry.

**Comment by kjjdejong** [comment]
Hee Erwin,

Ik heb thuis een Byron DB401E die wil ik graag toevoegen aan mijn homey, kun je mij daarbij helpen?

**Comment by erwindon** [comment]
@kjjdejong ja, die had ik ook. deze driver heb ik nooit goed werkend gekregen. maar experimenteer er gerust mee verder. wat is je concrete vraag?

**Comment by kjjdejong** [comment]
Hee,

Eerlijk gezegd zojuist in de prullenbak gegooid en een slimme deurbel
bestel van Eufy. De Byron hing hier nog van de oude bewoners...

Gr

Op ma 29 mrt. 2021 om 23:34 schreef Erwin Dondorp ***@***.***>
