### ISSUE TITLE
Since Homey 1.5.13 (and now 2.0 rc-x) Byron DB411E doesnt work

### ISSUE THREAD

**Issue by Sjalabert** [erwindon/com.dondorp.homey.byrondb#2]
I've updated a few weeks ago my Homey to 1.5.13 and now a few weeks 2.0.0 RC-x. Since these update it's not possible to connect the 'Byron DB411E' as device. Pairing is NOK

**Comment by Sjalabert** [comment]
Hello :)

**Comment by Sjalabert** [comment]
Erwin, Did you have a look at the issue? :)

**Comment by erwindon** [comment]
@Sjalabert thanks again for the reminder. nothing has changed. and there are no new ideas on how to solve it. and I still do not no have time to actually look at it. I'll update the README.md to mention this better. I can transfer the project to anyone with a good motivation on request.
